version: '3.8'

services:
  backend:
    build: .
    container_name: go_app1
    ports:
      - "8080:5000"
    depends_on:
      - redis
      - rabbitmq

  backend2:
    build: .
    container_name: go_app2
    ports:
      - "8081:5000"
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - backend2

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"